### ISSUE TITLE
Signup returns 500 error when email is already used

### ISSUE THREAD

**Issue by Dalordish** [nchlswhttkr/mellophone#27]
Currently an error along the lines of: Request failed, response code 500 is returned. This is unclear to users and should be changed to something that conveys the nature of the error.

**Comment by nchlswhttkr** [comment]
Thanks @Dalordish, let me assign this to one of our contributors and we'll see what we can do!

**Comment by nchlswhttkr** [comment]
![A "peace out" GIF where the person fades away](https://media.giphy.com/media/Ru9sjtZ09XOEg/giphy.webp)

**Comment by nchlswhttkr** [comment]
On a more serious note, this is probably a good opportunity to figure out how to handle the display of error messages.

Most >400 responses include an `error` field, so showing that is probably best. In the case where the message is not particularly useful or relates more to logging, it could be removed.

In fact there should be more logging in general so debugging these things is easier, I'll look into that.

**Comment by Dalordish** [comment]
> Thanks @Dalordish, let me assign this to one of our contributors and we'll see what we can do!


![](https://i.imgur.com/AP8gZTv.png)

**Comment by Dalordish** [comment]
Also on a more serious note, it's a little strange that it's throwing a 500 error rather than something like a 403 - some error handling probably needs to happen to stop it from just throwing an error up the call stack and going "uhhh idk what's going on"

**Comment by nchlswhttkr** [comment]
Uncaught errors become 500s, since there is [no catch when creating a user throws](https://github.com/nchlswhttkr/mellophone/blob/6f0038b192a8c586e480f4ffdc81f860bef04371/mellophone/backend/controllers/identity.py#L37) as of yet :rofl:

**Comment by nchlswhttkr** [comment]
Shouldn't be too much trouble to implement, you can use `GenericViews.forbidden_response()`
